# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Jeremy Tuloup
has_binder: false
has_settings: false
kind: frontend
labextension_name: myextension
project_short_description: A JupyterLab extension providing a different custom default
    drive
python_name: myextension
repository: https://github.com/jtpio/jupyterlab-custom-default-drive
test: false

